[project]
name = "rocm-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.2",
    "redis>=7.1.0",
    "uvicorn>=0.40.0",
]
